data.file=data/data.json



users.save=true
users.need_login=false
users.allow_time_change=false

links.check_by_code=true
links.clear_time=6000
links.count=5
links.count_notification=3
links.time=43200
links.time_notification=1800
links.validation=^https?://.+
links.size=6
links.link=clck.ru/
links.alphabet=ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz
links.max_try=1000
